### ISSUE TITLE
merge all files in a folder

### ISSUE THREAD

**Issue by Serkan-Karacelikler** [falahati/PHP-MP3#5]
hi can I define mp3 files as array and convert them all at once?

**Comment by falahati** [comment]
What do you mean? What is the problem you are trying to solve? This library only parses MP3 files and does not convert them in any way.

This library currently loads the MP3 file into the memory and therefore I suggest having as less as a possible instance of it in the memory at each moment of time. Otherwise, you exhaust the memory pretty soon.

**Comment by Serkan-Karacelikler** [comment]
I've managed to merge multiple mp3 files thank you
